# Generated by Django 3.2.19 on 2023-05-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('comments', models.TextField()),
                ('rating', models.FloatField()),
                ('history', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.tasks')),
            ],
        ),
    ]
