# Generated by Django 3.2.19 on 2023-05-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_clients_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='history',
        ),
        migrations.AddField(
            model_name='clients',
            name='history',
            field=models.ManyToManyField(to='website.Tasks'),
        ),
    ]
