# Generated by Django 3.2.19 on 2023-05-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20230513_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='rating',
        ),
        migrations.AddField(
            model_name='clients',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.RemoveField(
            model_name='clients',
            name='history',
        ),
        migrations.AddField(
            model_name='clients',
            name='history',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='name',
        ),
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.ManyToManyField(null=True, to='website.Clients'),
        ),
    ]
