# Generated by Django 3.2.19 on 2023-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20230513_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
