# Generated by Django 3.2.19 on 2023-05-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20230513_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='surname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='money',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='name',
        ),
        migrations.AddField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='potok',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='room',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
