# Generated by Django 3.2.19 on 2023-05-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_tasks_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='comments',
            field=models.TextField(null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='first_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='history',
            field=models.TextField(null=True, verbose_name='История посещений'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='rating',
            field=models.FloatField(default=5, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='surname',
            field=models.CharField(max_length=50, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='money',
            field=models.CharField(max_length=50, null=True, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='phone',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='potok',
            field=models.CharField(max_length=50, null=True, verbose_name='Дата начала недели'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='room',
            field=models.CharField(max_length=50, null=True, verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(max_length=50, null=True, verbose_name='Статус'),
        ),
    ]
