# Generated by Django 3.2.19 on 2023-05-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20230513_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='rating',
            field=models.FloatField(default=10, null=True, verbose_name='Рейтинг'),
        ),
    ]
