# Generated by Django 3.2.19 on 2023-05-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_clients_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='surname',
        ),
    ]
