# Generated by Django 3.2.19 on 2023-05-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_clients_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='comments',
            field=models.TextField(default='---', null=True, verbose_name='Комментарии'),
        ),
    ]
