# Generated by Django 3.2.19 on 2023-05-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_clients_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='clients',
            field=models.ManyToManyField(null=True, to='website.Clients', verbose_name='ФИО'),
        ),
    ]
