# Generated by Django 3.2.19 on 2023-05-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_tasks_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='clients',
            field=models.ManyToManyField(default='-----', null=True, to='website.Clients', verbose_name='Клиент'),
        ),
    ]
