# Generated by Django 3.2.19 on 2023-05-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_alter_tasks_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.clients')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.tasks')),
            ],
        ),
    ]
