# Generated by Django 3.2.19 on 2023-05-18 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_testtable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtable',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.clients'),
        ),
        migrations.AlterField(
            model_name='testtable',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.tasks'),
        ),
    ]
