# Generated by Django 3.2.19 on 2023-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20230518_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='clients',
            field=models.ManyToManyField(null=True, related_name='taski', to='website.Clients', verbose_name='Клиент'),
        ),
    ]
