# Generated by Django 3.2.19 on 2023-05-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_alter_tasks_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='clients',
            field=models.ManyToManyField(related_name='taski', to='website.Clients', verbose_name='Клиент'),
        ),
    ]
