# Generated by Django 3.2.19 on 2023-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_tasks_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='photo_passport',
            field=models.ImageField(null=True, upload_to='passport/%Y/%m/%d/', verbose_name='Фото паспорта'),
        ),
        migrations.AddField(
            model_name='clients',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
