# Generated by Django 3.2.19 on 2023-06-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20230525_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['-created_at'], 'verbose_name': 'Клиенты', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Фамилия')),
                ('photo_passport', models.ImageField(null=True, upload_to='passport/%Y/%m/%d/', verbose_name='Фото паспорта')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Номер телефона')),
                ('age', models.IntegerField(null=True, verbose_name='Год рождения')),
                ('rating', models.FloatField(default=10, null=True, verbose_name='Рейтинг')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата обновления')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.divisions')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['-created_at'],
            },
        ),
    ]
