# Generated by Django 3.2.19 on 2023-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20230626_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='divisions',
            options={'ordering': ['id'], 'verbose_name': 'Подразделения', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сотрудники', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.CharField(max_length=50, null=True, verbose_name='Дата рождения'),
        ),
    ]
